name: Check Website (Selenium)

# on:
#   schedule:
#     - cron: "0 8 * * *"
#     - cron: "0 20 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: ${{ secrets.TARGET_URL }}
      SEARCH_TERM: ${{ secrets.SEARCH_TERM }}
      SEARCH_INPUT_SELECTOR: ${{ secrets.SEARCH_INPUT_SELECTOR }}
      RESULT_SELECTOR: ${{ secrets.RESULT_SELECTOR }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
      TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous result
        uses: actions/download-artifact@v4
        with:
          name: past-results
          path: results

      - name: Run check
        run: python src/check.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: past-results
          path: results/past_results.json
          retention-days: 1
